export type Fixture = {
  id: string;
  date: string;
  time: string;
  home: string;
  away: string;
  league: "CPL" | "MLS";
  venue: string;
};

/** Upcoming fixtures for Canadian CPL & MLS clubs (2026 season sample). */
export const UPCOMING_FIXTURES: Fixture[] = [
  {
    id: "cpl-1",
    date: "2026-07-05",
    time: "16:00 ET",
    home: "Forge FC",
    away: "York United FC",
    league: "CPL",
    venue: "Tim Hortons Field, Hamilton",
  },
  {
    id: "cpl-2",
    date: "2026-07-05",
    time: "19:00 ET",
    home: "Atlético Ottawa",
    away: "Valour FC",
    league: "CPL",
    venue: "TD Place, Ottawa",
  },
  {
    id: "mls-1",
    date: "2026-07-05",
    time: "19:30 ET",
    home: "Toronto FC",
    away: "New York City FC",
    league: "MLS",
    venue: "BMO Field, Toronto",
  },
  {
    id: "cpl-3",
    date: "2026-07-06",
    time: "19:00 MT",
    home: "Cavalry FC",
    away: "FC Edmonton",
    league: "CPL",
    venue: "ATCO Field, Calgary",
  },
  {
    id: "mls-2",
    date: "2026-07-06",
    time: "22:00 ET",
    home: "Vancouver Whitecaps FC",
    away: "LA Galaxy",
    league: "MLS",
    venue: "BC Place, Vancouver",
  },
  {
    id: "cpl-4",
    date: "2026-07-08",
    time: "19:00 ET",
    home: "Halifax Wanderers FC",
    away: "Pacific FC",
    league: "CPL",
    venue: "Wanderers Grounds, Halifax",
  },
  {
    id: "cpl-5",
    date: "2026-07-09",
    time: "19:00 PT",
    home: "Vancouver FC",
    away: "Forge FC",
    league: "CPL",
    venue: "Willoughby Community Park, Langley",
  },
  {
    id: "mls-3",
    date: "2026-07-11",
    time: "19:30 ET",
    home: "CF Montréal",
    away: "Inter Miami CF",
    league: "MLS",
    venue: "Stade Saputo, Montréal",
  },
  {
    id: "cpl-6",
    date: "2026-07-12",
    time: "16:00 ET",
    home: "York United FC",
    away: "Cavalry FC",
    league: "CPL",
    venue: "York Stadium, Toronto",
  },
  {
    id: "cpl-7",
    date: "2026-07-12",
    time: "19:00 ET",
    home: "Valour FC",
    away: "Atlético Ottawa",
    league: "CPL",
    venue: "Princess Auto Stadium, Winnipeg",
  },
  {
    id: "mls-4",
    date: "2026-07-12",
    time: "19:30 ET",
    home: "Toronto FC",
    away: "Columbus Crew",
    league: "MLS",
    venue: "BMO Field, Toronto",
  },
  {
    id: "cpl-8",
    date: "2026-07-13",
    time: "19:00 MT",
    home: "FC Edmonton",
    away: "Pacific FC",
    league: "CPL",
    venue: "Clarke Stadium, Edmonton",
  },
  {
    id: "mls-5",
    date: "2026-07-13",
    time: "22:00 ET",
    home: "Vancouver Whitecaps FC",
    away: "Seattle Sounders FC",
    league: "MLS",
    venue: "BC Place, Vancouver",
  },
  {
    id: "cpl-9",
    date: "2026-07-15",
    time: "19:00 ET",
    home: "Forge FC",
    away: "Halifax Wanderers FC",
    league: "CPL",
    venue: "Tim Hortons Field, Hamilton",
  },
  {
    id: "cpl-10",
    date: "2026-07-16",
    time: "19:00 PT",
    home: "Pacific FC",
    away: "Vancouver FC",
    league: "CPL",
    venue: "Starlight Stadium, Langford",
  },
  {
    id: "mls-6",
    date: "2026-07-18",
    time: "19:30 ET",
    home: "CF Montréal",
    away: "Toronto FC",
    league: "MLS",
    venue: "Stade Saputo, Montréal",
  },
  {
    id: "cpl-11",
    date: "2026-07-19",
    time: "16:00 ET",
    home: "Atlético Ottawa",
    away: "Forge FC",
    league: "CPL",
    venue: "TD Place, Ottawa",
  },
  {
    id: "cpl-12",
    date: "2026-07-19",
    time: "19:00 ET",
    home: "York United FC",
    away: "Halifax Wanderers FC",
    league: "CPL",
    venue: "York Stadium, Toronto",
  },
  {
    id: "mls-7",
    date: "2026-07-19",
    time: "22:00 ET",
    home: "Vancouver Whitecaps FC",
    away: "Portland Timbers",
    league: "MLS",
    venue: "BC Place, Vancouver",
  },
  {
    id: "cpl-13",
    date: "2026-07-20",
    time: "19:00 MT",
    home: "Cavalry FC",
    away: "Vancouver FC",
    league: "CPL",
    venue: "ATCO Field, Calgary",
  },
  {
    id: "cpl-14",
    date: "2026-07-22",
    time: "19:00 ET",
    home: "Valour FC",
    away: "FC Edmonton",
    league: "CPL",
    venue: "Princess Auto Stadium, Winnipeg",
  },
  {
    id: "mls-8",
    date: "2026-07-25",
    time: "19:30 ET",
    home: "Toronto FC",
    away: "CF Montréal",
    league: "MLS",
    venue: "BMO Field, Toronto",
  },
  {
    id: "cpl-15",
    date: "2026-07-26",
    time: "16:00 ET",
    home: "Halifax Wanderers FC",
    away: "Cavalry FC",
    league: "CPL",
    venue: "Wanderers Grounds, Halifax",
  },
  {
    id: "cpl-16",
    date: "2026-07-26",
    time: "19:00 PT",
    home: "Pacific FC",
    away: "Atlético Ottawa",
    league: "CPL",
    venue: "Starlight Stadium, Langford",
  },
  {
    id: "mls-9",
    date: "2026-07-26",
    time: "22:00 ET",
    home: "Vancouver Whitecaps FC",
    away: "Minnesota United FC",
    league: "MLS",
    venue: "BC Place, Vancouver",
  },
];

export function formatFixtureDate(isoDate: string): string {
  const date = new Date(`${isoDate}T12:00:00`);
  return date.toLocaleDateString("en-CA", {
    weekday: "short",
    month: "short",
    day: "numeric",
  });
}
