const HERITAGE_FLAG_MAP: Record<string, string> = {
  afghanistan: "🇦🇫",
  albania: "🇦🇱",
  algeria: "🇩🇿",
  argentina: "🇦🇷",
  armenia: "🇦🇲",
  australia: "🇦🇺",
  bangladesh: "🇧🇩",
  brazil: "🇧🇷",
  britain: "🇬🇧",
  bulgaria: "🇧🇬",
  cambodia: "🇰🇭",
  cameroon: "🇨🇲",
  canada: "🇨🇦",
  chile: "🇨🇱",
  china: "🇨🇳",
  colombia: "🇨🇴",
  congo: "🇨🇩",
  croatia: "🇭🇷",
  cuba: "🇨🇺",
  czech: "🇨🇿",
  czechia: "🇨🇿",
  denmark: "🇩🇰",
  egypt: "🇪🇬",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  eritrea: "🇪🇷",
  ethiopia: "🇪🇹",
  filipino: "🇵🇭",
  filipinas: "🇵🇭",
  finland: "🇫🇮",
  france: "🇫🇷",
  french: "🇫🇷",
  germany: "🇩🇪",
  german: "🇩🇪",
  ghana: "🇬🇭",
  greece: "🇬🇷",
  greek: "🇬🇷",
  guatemala: "🇬🇹",
  haiti: "🇭🇹",
  haitian: "🇭🇹",
  india: "🇮🇳",
  indian: "🇮🇳",
  indonesia: "🇮🇩",
  iran: "🇮🇷",
  iraq: "🇮🇶",
  ireland: "🇮🇪",
  irish: "🇮🇪",
  israel: "🇮🇱",
  italy: "🇮🇹",
  italian: "🇮🇹",
  ivorian: "🇨🇮",
  "ivory coast": "🇨🇮",
  jamaica: "🇯🇲",
  jamaican: "🇯🇲",
  japan: "🇯🇵",
  jordan: "🇯🇴",
  kenya: "🇰🇪",
  korea: "🇰🇷",
  korean: "🇰🇷",
  lebanon: "🇱🇧",
  lebanese: "🇱🇧",
  liberia: "🇱🇷",
  liberian: "🇱🇷",
  mexico: "🇲🇽",
  mexican: "🇲🇽",
  morocco: "🇲🇦",
  netherlands: "🇳🇱",
  dutch: "🇳🇱",
  newfoundland: "🇨🇦",
  nigeria: "🇳🇬",
  nigerian: "🇳🇬",
  norway: "🇳🇴",
  pakistan: "🇵🇰",
  pakistani: "🇵🇰",
  palestine: "🇵🇸",
  palestinian: "🇵🇸",
  peru: "🇵🇪",
  philippines: "🇵🇭",
  poland: "🇵🇱",
  polish: "🇵🇱",
  portugal: "🇵🇹",
  portuguese: "🇵🇹",
  punjab: "🇮🇳",
  punjabi: "🇮🇳",
  romania: "🇷🇴",
  russia: "🇷🇺",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  serbia: "🇷🇸",
  somalia: "🇸🇴",
  somali: "🇸🇴",
  spain: "🇪🇸",
  spanish: "🇪🇸",
  sri: "🇱🇰",
  "sri lanka": "🇱🇰",
  sweden: "🇸🇪",
  swedish: "🇸🇪",
  syria: "🇸🇾",
  syrian: "🇸🇾",
  taiwan: "🇹🇼",
  thailand: "🇹🇭",
  tunisia: "🇹🇳",
  turkey: "🇹🇷",
  turkish: "🇹🇷",
  ukraine: "🇺🇦",
  ukrainian: "🇺🇦",
  "united kingdom": "🇬🇧",
  uk: "🇬🇧",
  usa: "🇺🇸",
  vietnam: "🇻🇳",
  vietnamese: "🇻🇳",
  wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  zimbabwe: "🇿🇼",
};

export function getHeritageFlag(heritage: string): string {
  const normalized = heritage.trim().toLowerCase();
  if (!normalized) return "🌍";

  if (HERITAGE_FLAG_MAP[normalized]) return HERITAGE_FLAG_MAP[normalized];

  for (const [key, flag] of Object.entries(HERITAGE_FLAG_MAP)) {
    if (normalized.includes(key) || key.includes(normalized)) return flag;
  }

  return "🌍";
}
