export type StaffMember = {
  name: string;
  role: string;
};

export type TournamentCampaign = {
  id: string;
  year: number;
  tournament: string;
  hostCountry: string;
  result: string;
  headCoach: string;
  auxiliares: StaffMember[];
  squad: string[];
  story: string;
  milestone: string;
};

export const MENS_HISTORY: TournamentCampaign[] = [
  {
    id: "mnt-1985",
    year: 1985,
    tournament: "CONCACAF Championship",
    hostCountry: "Multiple (Home & Away)",
    result: "Champions 🏆",
    headCoach: "Tony Waiters",
    auxiliares: [
      { name: "Bob Bearpark", role: "Assistant Coach" },
      { name: "Les Wilson", role: "Team Manager" },
    ],
    squad: [
      "Paul Dolan",
      "Sven Habermann",
      "Tino Lettieri",
      "Ian Baird",
      "Ian Bridge",
      "Bob Lenarduzzi",
      "Terry Moore",
      "Randy Samuel",
      "Bruce Wilson",
      "Shaun Lowther",
      "Pasquale De Luca",
      "Gerry Gray",
      "Paul James",
      "David Norman",
      "Randy Ragan",
      "Mike Sweeney",
      "John Catliff",
      "Ken Garraway",
      "Mark Karpun",
      "Dale Mitchell",
      "George Pakos",
      "Carl Valentine",
      "Igor Vrablic",
    ],
    story:
      "The legendary campaign that secured Canada's first-ever qualification for a men's FIFA World Cup. Sealed with an unforgettable 2-1 victory over Honduras on a freezing afternoon in St. John's, Newfoundland, this triumph established a blueprint for Canadian team unity.",
    milestone: "First CONCACAF Championship crown.",
  },
  {
    id: "mnt-1986",
    year: 1986,
    tournament: "FIFA World Cup",
    hostCountry: "Mexico",
    result: "Group Stage",
    headCoach: "Tony Waiters",
    auxiliares: [
      { name: "Bob Bearpark", role: "Assistant Coach" },
      { name: "Les Wilson", role: "Team Manager" },
    ],
    squad: [
      "Tino Lettieri",
      "Bob Lenarduzzi",
      "Bruce Wilson",
      "Randy Ragan",
      "Terry Moore",
      "Ian Bridge",
      "Carl Valentine",
      "Gerry Gray",
      "Branko Segota",
      "Igor Vrablic",
      "Mike Sweeney",
      "Randy Samuel",
      "George Pakos",
      "Dale Mitchell",
      "Paul James",
      "Greg Ion",
      "David Norman",
      "Jamie Lowery",
      "Pasquale De Luca",
      "Colin Miller",
      "Sven Habermann",
      "Paul Dolan",
    ],
    story:
      "The pioneering crew that shocked the sporting landscape by qualifying out of CONCACAF with little money and no domestic league. In Mexico, Captain Bruce Wilson and former NASL stars held global powers like France to an agonizingly close 1-0 battle, laying down the baseline grit for Canadian soccer history.",
    milestone: "Historic World Cup debut campaign.",
  },
  {
    id: "mnt-2000",
    year: 2000,
    tournament: "CONCACAF Gold Cup",
    hostCountry: "United States",
    result: "Champions 🏆",
    headCoach: "Holger Osieck",
    auxiliares: [
      { name: "Ray Clark", role: "Assistant Coach" },
      { name: "Morgan Quarry", role: "Team Manager" },
    ],
    squad: [
      "Craig Forrest",
      "Paul Fenwick",
      "Tony Menezes",
      "Jason de Vos",
      "Paul Stalteri",
      "Carlo Corazzin",
      "Davide Xausa",
      "Jim Brennan",
      "Jeff Clarke",
      "Mark Watson",
      "Richard Hastings",
      "Garret Kusch",
      "Paul Peschisolido",
      "Elvis Thomas",
      "Martin Nash",
      "Pat Onstad",
      "Robbie Aristodemo",
      "Dwayne De Rosario",
    ],
    story:
      "One of the greatest underdog runs in regional history. Canada survived a coin-toss group-stage tiebreaker, went on to shock soccer giants Mexico in the quarter-finals, and defeated Colombia - to lift the Gold Cup trophy. Goalkeeper Craig Forrest took home MVP honors after saving tournament-defining penalties.",
    milestone: "Historic modern Gold Cup triumph.",
  },
  {
    id: "mnt-2022",
    year: 2022,
    tournament: "FIFA World Cup",
    hostCountry: "Qatar",
    result: "Group Stage",
    headCoach: "John Herdman",
    auxiliares: [
      { name: "Mauro Biello", role: "Assistant Coach" },
      { name: "Eric Tenllado", role: "Assistant Coach & Performance Lead" },
      { name: "Simon Eaddy", role: "Goalkeeper Coach" },
      { name: "Robyn Gayle", role: "Mental & Cultural Performance Coach" },
    ],
    squad: [
      "Milan Borjan",
      "James Pantemis",
      "Dayne St. Clair",
      "Samuel Adekugbe",
      "Derek Cornelius",
      "Alistair Johnston",
      "Richie Laryea",
      "Kamal Miller",
      "Steven Vitória",
      "Joel Waterman",
      "Stephen Eustáquio",
      "Liam Fraser",
      "Atiba Hutchinson",
      "Mark-Anthony Kaye",
      "Ismaël Koné",
      "Jonathan Osorio",
      "Samuel Piette",
      "David Wotherspoon",
      "Tajon Buchanan",
      "Lucas Cavallini",
      "Jonathan David",
      "Alphonso Davies",
      "Junior Hoilett",
      "Cyle Larin",
      "Liam Millar",
      "Ike Ugbo",
    ],
    story:
      "The generation that broke the 36-year curse by topping CONCACAF qualification with an unbeaten run on freezing home-soil nights. In Qatar, Alphonso Davies scored the country's historic first-ever Men's World Cup goal against Croatia with a booming header just 68 seconds into kickoff, announcing a new era.",
    milestone: "First tournament goal scored.",
  },
  {
    id: "mnt-2024",
    year: 2024,
    tournament: "Copa América",
    hostCountry: "United States",
    result: "4th Place Finish",
    headCoach: "Jesse Marsch",
    auxiliares: [
      { name: "Mauro Biello", role: "Assistant Coach" },
      { name: "Ewan Sharp", role: "Assistant Coach & Analyst" },
      { name: "Pierre Barrieu", role: "Head of Performance" },
    ],
    squad: [
      "Dayne St. Clair",
      "Alistair Johnston",
      "Luc de Fougerolles",
      "Kamal Miller",
      "Joel Waterman",
      "Samuel Piette",
      "Stephen Eustáquio",
      "Ismaël Koné",
      "Cyle Larin",
      "Jonathan David",
      "Theo Bair",
      "Jacen Russell-Rowe",
      "Derek Cornelius",
      "Jacob Shaffelburg",
      "Moïse Bombito",
      "Maxime Crépeau",
      "Tajon Buchanan",
      "Tom McGill",
      "Alphonso Davies",
      "Ali Ahmed",
      "Jonathan Osorio",
      "Richie Laryea",
      "Liam Millar",
      "Mathieu Choinière",
      "Tani Oluwaseyi",
      "Kyle Hiebert",
    ],
    story:
      "A sensational, aggressive debut tournament under newly appointed coach Jesse Marsch. Stepping into South America's prestigious tournament as wildcards, Canada battled past world powers like Chile, survived a dramatic shootout win over Venezuela, and marched all the way to a historic Top-4 global finish.",
    milestone: "Unforgettable Copa América semi-final run.",
  },
  {
    id: "mnt-2026",
    year: 2026,
    tournament: "FIFA World Cup",
    hostCountry: "Canada / USA / Mexico",
    result: "Knockout Run",
    headCoach: "Jesse Marsch",
    auxiliares: [
      { name: "Mauro Biello", role: "Assistant Coach" },
      { name: "Ewan Sharp", role: "Assistant Coach" },
      { name: "Pierre Barrieu", role: "Head of Performance" },
      { name: "Jan Lang", role: "Team Manager" },
    ],
    squad: [
      "Dayne St. Clair",
      "Alistair Johnston",
      "Alfie Jones",
      "Luc de Fougerolles",
      "Joel Waterman",
      "Mathieu Choinière",
      "Stephen Eustáquio",
      "Ismaël Koné",
      "Cyle Larin",
      "Jonathan David",
      "Liam Millar",
      "Tani Oluwaseyi",
      "Derek Cornelius",
      "Jacob Shaffelburg",
      "Moïse Bombito",
      "Maxime Crépeau",
      "Tajon Buchanan",
      "Owen Goodman",
      "Alphonso Davies",
      "Ali Ahmed",
      "Jonathan Osorio",
      "Richie Laryea",
      "Niko Sigur",
      "Promise David",
      "Nathan Saliba",
      "Jayden Nelson",
    ],
    story:
      "Playing on home soil in front of rocking, sold-out stands from Vancouver to Toronto. Re-energized by a high-intensity press tactical identity, Les Rouges translated home-crowd passion into a historic, unforgettable run deep into the expanded tournament bracket, cementing soccer as a mainstream Canadian obsession.",
    milestone: "Historic knockout achievement on home soil.",
  },
];

export const WOMENS_HISTORY: TournamentCampaign[] = [
  {
    id: "wnt-1995",
    year: 1995,
    tournament: "FIFA Women's World Cup",
    hostCountry: "Sweden",
    result: "Group Stage",
    headCoach: "Sylvie Béliveau",
    auxiliares: [{ name: "Joan McEachern", role: "Technical Support" }],
    squad: [
      "Wendy Hawthorne",
      "Helen Stoumbos",
      "Charmaine Hooper",
      "Michelle Ring",
      "Andrea Neil",
      "Geri Donnelly",
      "Isabelle Morneau",
      "Nicole Sedgwick",
      "Janine Helland",
      "Veronica O'Brien",
      "Annie Caron",
      "Joan McEachern",
      "Angela Kelly",
      "Cathy Ross",
      "Suzanne Muir",
      "Luce Mongrain",
      "Silvana Burtini",
      "Carla Chin",
      "Suzanne Gerrior",
      "Tania Singfield",
    ],
    story:
      "Canada's historic entry into the elite echelons of global women's football. Led by coach Sylvie Béliveau, this trailblazing group fought through group-stage battles against England and Norway, writing the opening blueprint for high-performance women's sports development under the Maple Leaf.",
    milestone: "Inaugural Women's World Cup appearance.",
  },
  {
    id: "wnt-1998",
    year: 1998,
    tournament: "CONCACAF Women's Championship",
    hostCountry: "Canada",
    result: "Champions 🏆",
    headCoach: "Neil Turnbull",
    auxiliares: [{ name: "Cathy Blue", role: "Team Manager" }],
    squad: [
      "Nicole Wright",
      "Karina LeBlanc",
      "Marie-Claude Dion",
      "Charmaine Hooper",
      "Isabelle Morneau",
      "Suzanne Muir",
      "Cindy Walsh",
      "Geraldine Donnelly",
      "Tanya Franck",
      "Isabelle Harvey",
      "Sarah Joly",
      "Stephanie O'Neil",
      "Liz Smith",
      "Amy Walsh",
      "Tina Blaskovic",
      "Silvana Burtini",
      "Shannon Rosenow",
      "Helen Stoumbos",
    ],
    story:
      "Dominance on home soil. Canada tore through the CONCACAF Championship tournament in Toronto, scoring 42 goals and conceding zero across five consecutive games, culminating in a clinical 1-0 win over Mexico to lift the trophy and secure a dominant path forward.",
    milestone: "First CONCACAF W Championship crown.",
  },
  {
    id: "wnt-2003",
    year: 2003,
    tournament: "FIFA Women's World Cup",
    hostCountry: "United States",
    result: "4th Place Finish",
    headCoach: "Even Pellerud",
    auxiliares: [{ name: "Ian Bridge", role: "Assistant Coach" }],
    squad: [
      "Karina LeBlanc",
      "Christine Latham",
      "Linda Hathorn",
      "Sasha Andrews",
      "Andrea Neil",
      "Sharolta Nonen",
      "Isabelle Morneau",
      "Kristina Kiss",
      "Rhian Wilkinson",
      "Charmaine Hooper",
      "Randee Hermus",
      "Christine Sinclair",
      "Diana Matheson",
      "Carmelina Moscato",
      "Kara Lang",
      "Brittany Baxter",
      "Silvana Burtini",
      "Tanya Dennis",
      "Erin McLeod",
      "Taryn Swiatek",
    ],
    story:
      "A legendary, transcendent breakthrough. Under Norwegian mentor Even Pellerud, Canada charged through the knockouts—shocking regional giants to secure a historic fourth-place global finish. This was the exact launchpad tournament that witnessed the definitive rise of a young captain named Christine Sinclair.",
    milestone: "Historic Top-4 global finish.",
  },
  {
    id: "wnt-2010",
    year: 2010,
    tournament: "CONCACAF Women's Championship",
    hostCountry: "Mexico",
    result: "Champions 🏆",
    headCoach: "Carolina Morace",
    auxiliares: [{ name: "Elisabetta Bavagnoli", role: "Assistant Coach" }],
    squad: [
      "Karina LeBlanc",
      "Emily Zurrer",
      "Desiree Scott",
      "Carmelina Moscato",
      "Robyn Gayle",
      "Kaylyn Kyle",
      "Rhian Wilkinson",
      "Diana Matheson",
      "Candace Chapman",
      "Christina Julien",
      "Josée Bélanger",
      "Christine Sinclair",
      "Sophie Schmidt",
      "Melissa Tancredi",
      "Kara Lang",
      "Jonelle Filigno",
      "Chelsea Stewart",
      "Brooke McCalla",
      "Marie-Ève Nault",
      "Stephanie Labbé",
    ],
    story:
      "A masterclass performance in Cancun, Mexico. Carolina Morace's squad won every single match without conceding a single goal, defeating the host nation Mexico 1-0 in the final to claim regional dominance and showcase tactical growth.",
    milestone: "Second CONCACAF continental title.",
  },
  {
    id: "wnt-2012",
    year: 2012,
    tournament: "London Olympic Games",
    hostCountry: "United Kingdom",
    result: "Bronze Medal 🥉",
    headCoach: "John Herdman",
    auxiliares: [
      { name: "Bev Priestman", role: "Assistant Coach" },
      { name: "Simon Eaddy", role: "Goalkeeper Coach" },
    ],
    squad: [
      "Karina LeBlanc",
      "Erin McLeod",
      "Candace Chapman",
      "Carmelina Moscato",
      "Emily Zurrer",
      "Robyn Gayle",
      "Lauren Sesselmann",
      "Chelsea Stewart",
      "Rhian Wilkinson",
      "Kaylyn Kyle",
      "Diana Matheson",
      "Kelly Parker",
      "Sophie Schmidt",
      "Desiree Scott",
      "Jonelle Filigno",
      "Christine Sinclair",
      "Melissa Tancredi",
      "Brittany Timko",
    ],
    story:
      "The tournament that changed Canadian sports culture forever. Following a controversial and heartbreaking semi-final battle against the USA at Old Trafford, the squad rallied fiercely. Diana Matheson scored a dramatic 92nd-minute winner against France to secure the country's first team-sport Olympic medal since 1936.",
    milestone: "Historic Olympic Bronze medal breakthrough.",
  },
  {
    id: "wnt-2015",
    year: 2015,
    tournament: "FIFA Women's World Cup",
    hostCountry: "Canada",
    result: "Quarter-Finals",
    headCoach: "John Herdman",
    auxiliares: [
      { name: "Bev Priestman", role: "Assistant Coach" },
      { name: "Simon Eaddy", role: "Goalkeeper Coach" },
      { name: "Robyn Gayle", role: "Cultural Manager" },
    ],
    squad: [
      "Stephanie Labbé",
      "Karina LeBlanc",
      "Erin McLeod",
      "Kadeisha Buchanan",
      "Allysha Chapman",
      "Robyn Gayle",
      "Carmelina Moscato",
      "Marie-Ève Nault",
      "Lauren Sesselmann",
      "Rhian Wilkinson",
      "Emily Zurrer",
      "Jessie Fleming",
      "Selenia Iacchelli",
      "Kaylyn Kyle",
      "Ashley Lawrence",
      "Diana Matheson",
      "Desiree Scott",
      "Sophie Schmidt",
      "Josée Bélanger",
      "Jonelle Filigno",
      "Adriana Leon",
      "Christine Sinclair",
      "Melissa Tancredi",
    ],
    story:
      "A historic, soaring celebration of soccer across home soil. Playing in front of record-breaking crowds from coast to coast, Herdman's squad advanced into the quarter-finals, turning the entire country into a sea of red and cementing the women's team as mainstream national heroes.",
    milestone: "Record-breaking home attendance.",
  },
  {
    id: "wnt-2016",
    year: 2016,
    tournament: "Rio Olympic Games",
    hostCountry: "Brazil",
    result: "Bronze Medal 🥉",
    headCoach: "John Herdman",
    auxiliares: [
      { name: "Bev Priestman", role: "Assistant Coach" },
      { name: "Simon Eaddy", role: "Goalkeeper Coach" },
    ],
    squad: [
      "Stephanie Labbé",
      "Sabrina D'Angelo",
      "Kadeisha Buchanan",
      "Rebecca Quinn",
      "Shelina Zadorsky",
      "Josée Bélanger",
      "Allysha Chapman",
      "Rhian Wilkinson",
      "Jessie Fleming",
      "Ashley Lawrence",
      "Diana Matheson",
      "Deanne Rose",
      "Sophie Schmidt",
      "Desiree Scott",
      "Janine Beckie",
      "Nichelle Prince",
      "Christine Sinclair",
      "Melissa Tancredi",
    ],
    story:
      "Consolidation of greatness. Canada went on a sensational run in Brazil, defeating powerhouse nations like Germany and France. In the Bronze medal match, goals from teenage sensation Deanne Rose and captain Christine Sinclair secured consecutive Olympic podiums, proving Canada belonged to the global elite.",
    milestone: "Back-to-back Olympic medals.",
  },
  {
    id: "wnt-2020",
    year: 2021,
    tournament: "Tokyo Olympic Games",
    hostCountry: "Japan",
    result: "Gold Medal 🥇",
    headCoach: "Bev Priestman",
    auxiliares: [
      { name: "Andy Spence", role: "Assistant Coach" },
      { name: "Jen Herst", role: "Goalkeeper Coach" },
    ],
    squad: [
      "Stephanie Labbé",
      "Kailen Sheridan",
      "Erin McLeod",
      "Kadeisha Buchanan",
      "Allysha Chapman",
      "Ashley Lawrence",
      "Jayde Riviere",
      "Gabrielle Carle",
      "Vanessa Gilles",
      "Shelina Zadorsky",
      "Jessie Fleming",
      "Julia Grosso",
      "Quinn",
      "Desiree Scott",
      "Sophie Schmidt",
      "Janine Beckie",
      "Adriana Leon",
      "Nichelle Prince",
      "Deanne Rose",
      "Christine Sinclair",
      "Évelyne Viens",
      "Jordyn Huitema",
    ],
    story:
      "Absolute global immortality. Bev Priestman's squad navigated a grueling, tactical path to the final in Yokohama. Following clutch penalty heroics from Jessie Fleming and goalkeeper Stephanie Labbé throughout the knockouts, Julia Grosso scored the legendary winning spot-kick in a dramatic shootout against Sweden, crowning Canada Olympic Champions.",
    milestone: "Olympic Gold. Champions of the world.",
  },
  {
    id: "wnt-2023",
    year: 2023,
    tournament: "FIFA Women's World Cup",
    hostCountry: "Australia / New Zealand",
    result: "Group Stage",
    headCoach: "Bev Priestman",
    auxiliares: [
      { name: "Andy Spence", role: "Assistant Coach" },
      { name: "Jasmine Mander", role: "Assistant Coach" },
      { name: "Jen Herst", role: "Goalkeeper Coach" },
    ],
    squad: [
      "Kailen Sheridan",
      "Allysha Chapman",
      "Kadeisha Buchanan",
      "Shelina Zadorsky",
      "Quinn",
      "Deanne Rose",
      "Julia Grosso",
      "Jayde Riviere",
      "Jordyn Huitema",
      "Ashley Lawrence",
      "Évelyne Viens",
      "Christine Sinclair",
      "Sophie Schmidt",
      "Vanessa Gilles",
      "Nichelle Prince",
      "Gabrielle Carle",
      "Jessie Fleming",
      "Sabrina D'Angelo",
      "Adriana Leon",
      "Cloé Lacasse",
      "Simi Awujo",
      "Lysianne Proulx",
      "Olivia Smith",
    ],
    story:
      "Entering the Southern Hemisphere as reigning Olympic Gold champions, Canada faced deep tactical hurdles and injury constraints. While the tournament ended early, it served as the final international tournament curtain call for legendary captain Christine Sinclair, the greatest goalscorer in global game history.",
    milestone: "Sinclair's final World Cup campaign.",
  },
];
