export type Player = {
  id: string;
  name: string;
  number: number;
  position: string;
  bornIn: string;
  heritage: string;
  nowRepresents: string;
  tagline: string;
  story: string;
  quote: string;
  initials: string;
  imageUrl?: string;
  isHomegrown?: boolean;
};

function p(
  id: string,
  name: string,
  number: number,
  position: string,
  bornIn: string,
  heritage: string,
  nowRepresents: string,
  tagline: string,
  story: string,
  quote: string,
  imageUrl?: string,
  isHomegrown?: boolean,
): Player {
  const initials = name
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
  return {
    id,
    name,
    number,
    position,
    bornIn,
    heritage,
    nowRepresents,
    tagline,
    story,
    quote,
    initials,
    ...(imageUrl ? { imageUrl } : {}),
    ...(isHomegrown ? { isHomegrown } : {}),
  };
}

const CANADIAN_BORN_MARKERS = [
  "canada",
  " qc",
  ", qc",
  "québec",
  "quebec",
  " on",
  ", on",
  "ontario",
  " bc",
  ", bc",
  "british columbia",
  " ab",
  ", ab",
  "alberta",
  " sk",
  "saskatchewan",
  " mb",
  "manitoba",
  " nb",
  "brunswick",
  " ns",
  "scotia",
  " pe",
  "prince edward",
  " nl",
  "newfoundland",
  "labrador",
  "yukon",
  "nunavut",
  "northwest territories",
] as const;

function isBornInCanada(bornIn: string): boolean {
  const born = bornIn.toLowerCase();
  return CANADIAN_BORN_MARKERS.some((marker) => born.includes(marker));
}

export function isHomegrownPlayer(player: Player): boolean {
  if (player.isHomegrown) return true;
  if (!isBornInCanada(player.bornIn)) return false;

  const heritage = player.heritage.toLowerCase();
  return heritage === "canadian" || heritage === "french-canadian";
}

export const MENS_SQUAD: Player[] = [
  p(
    "alphonso-davies",
    "Alphonso Davies",
    19,
    "Left Back / Winger",
    "Buduburam, Liberia — refugee camp",
    "Liberian",
    "Edmonton, Alberta",
    "The heartbeat of our speed.",
    "Born in a refugee camp to parents who fled the Liberian civil war, Alphonso arrived in Edmonton as a child and became the pulse of a nation learning to believe.",
    "Every sprint down the flank is proof that the Canadian mosaic runs faster than anyone expected.",
  ),
  p(
    "jonathan-david",
    "Jonathan David",
    20,
    "Striker",
    "Brooklyn, New York",
    "Haitian",
    "Ottawa, Ontario",
    "The clinical finisher of the capital.",
    "Raised in Ottawa by Haitian parents, Jonathan turned a capital-city upbringing into a European scoring reputation Canada could build around.",
    "When I score for Canada, I carry Brooklyn, Port-au-Prince, and Ottawa in every celebration.",
  ),
  p(
    "ismael-kone",
    "Ismaël Koné",
    8,
    "Central Midfielder",
    "Abidjan, Ivory Coast",
    "Ivorian",
    "Montréal, Québec",
    "The midfield elegance of Quebec.",
    "Born in Abidjan and raised in Montréal, Ismaël glides through midfields with unmistakable grace and francophone flair.",
    "Montréal taught me flair; Canada gave me a stage to share it with the world.",
  ),
  p(
    "cyle-larin",
    "Cyle Larin",
    17,
    "Striker",
    "Brampton, Ontario",
    "Jamaican",
    "Brampton, Ontario",
    "The true north's leading talisman.",
    "Brampton-born with proud Jamaican heritage, Cyle became one of the most prolific scorers in Canadian men's history without ever leaving home.",
    "I never had to leave Canada to prove Canada belongs on the world stage.",
  ),
  p(
    "milan-borjan",
    "Milan Borjan",
    1,
    "Goalkeeper",
    "Knin, Croatia",
    "Serbian",
    "Hamilton, Ontario",
    "The wall between the posts.",
    "A veteran keeper whose Balkan roots and Ontario home forged an unshakeable last line of defence for Les Rouges.",
    "I've guarded this net across continents — but nowhere feels like defending Canada.",
  ),
  p(
    "sam-adekugbe",
    "Sam Adekugbe",
    3,
    "Left Back",
    "Calgary, Alberta",
    "Nigerian",
    "Vancouver, BC",
    "Relentless on the overlap.",
    "Calgary-born with Nigerian heritage, Sam embodies the modern Canadian full-back — athletic, intelligent, and fearless.",
    "My parents' journey to Canada is why I never take this jersey for granted.",
  ),
  p(
    "steven-vitoria",
    "Steven Vitória",
    5,
    "Centre Back",
    "Toronto, Ontario",
    "Portuguese",
    "Toronto, Ontario",
    "The veteran anchor.",
    "Portuguese-Canadian roots and years of European experience made Vitória the calm centre of Canada's defensive rebuild.",
    "Experience is my heritage gift to the next generation of Canadian defenders.",
  ),
  p(
    "richie-laryea",
    "Richie Laryea",
    2,
    "Right Back",
    "Toronto, Ontario",
    "Ghanaian",
    "Toronto, Ontario",
    "The engine on the right.",
    "Toronto-born with Ghanaian heritage, Laryea's overlapping runs and tireless work rate define Canada's modern full-back play.",
    "Every overlap is a thank-you to the community that raised me in Scarborough.",
  ),
  p(
    "kamal-miller",
    "Kamal Miller",
    4,
    "Centre Back",
    "Scarborough, Ontario",
    "Jamaican",
    "Toronto, Ontario",
    "Strength under pressure.",
    "Scarborough's Jamaican-Canadian community produced a centre-back whose physicality and composure anchor the back line.",
    "Scarborough made me tough; the maple leaf made me proud.",
  ),
  p(
    "derek-cornelius",
    "Derek Cornelius",
    13,
    "Centre Back",
    "Nassau, Bahamas",
    "Bahamian",
    "Vancouver, BC",
    "The composed commander.",
    "Born in the Bahamas and raised in Vancouver, Cornelius brings poise and leadership to every defensive action.",
    "Two homes, one country — that's the Canadian story I live every match.",
  ),
  p(
    "stephen-eustaquio",
    "Stephen Eustáquio",
    7,
    "Central Midfielder",
    "Leiria, Portugal",
    "Portuguese",
    "Toronto, Ontario",
    "The metronome in midfield.",
    "Portuguese-born and Toronto-raised, Eustáquio controls tempo with the vision of a playmaker forged in two football cultures.",
    "Portugal taught me technique; Canada taught me heart.",
  ),
  p(
    "mark-anthony-kaye",
    "Mark-Anthony Kaye",
    6,
    "Defensive Midfielder",
    "Toronto, Ontario",
    "Jamaican",
    "Toronto, Ontario",
    "The midfield shield.",
    "Jamaican-Canadian grit in the middle of the park — Kaye breaks up play and launches attacks with equal conviction.",
    "I break up attacks so my teammates can write Canadian history.",
  ),
  p(
    "liam-fraser",
    "Liam Fraser",
    18,
    "Defensive Midfielder",
    "Toronto, Ontario",
    "Jamaican",
    "Toronto, Ontario",
    "The quiet enforcer.",
    "A Toronto product with Jamaican roots who does the unglamorous work that lets Canada's stars shine.",
    "The mosaic works because every tile holds its place — that's my job.",
  ),
  p(
    "atiba-hutchinson",
    "Atiba Hutchinson",
    10,
    "Central Midfielder",
    "Brampton, Ontario",
    "Trinidadian",
    "Istanbul, Turkey",
    "Captain Canada. Legend forever.",
    "The Brampton boy who captained Canada through its darkest years and into the light — a living legend of the Canadian game.",
    "I stayed when it was hard, so the next generation could arrive when it was glorious.",
  ),
  p(
    "tajon-buchanan",
    "Tajon Buchanan",
    11,
    "Winger",
    "Brampton, Ontario",
    "Jamaican",
    "Brampton, Ontario",
    "Electric on the wing.",
    "Brampton's Jamaican-Canadian winger brings pace, trickery, and a fearless creativity that unlocks defences.",
    "Every nutmeg is a love letter to Brampton's pickup pitches.",
  ),
  p(
    "junior-hoilett",
    "Junior Hoilett",
    14,
    "Winger",
    "Bradford, England",
    "Jamaican",
    "Toronto, Ontario",
    "The experienced creator.",
    "Born in England to Jamaican parents and raised in Canada, Hoilett's craft and experience remain vital.",
    "Three countries shaped me — but only one jersey makes me cry.",
  ),
  p(
    "jacob-shaffelburg",
    "Jacob Shaffelburg",
    16,
    "Winger",
    "Bedford, Nova Scotia",
    "Canadian",
    "Bedford, NS",
    "Atlantic Canada's spark.",
    "Nova Scotia's own — proof that talent blooms on every coast of this vast country.",
    "They said Atlantic Canada couldn't produce a World Cup winger. I disagreed.",
  ),
  p(
    "lucas-cavallini",
    "Lucas Cavallini",
    9,
    "Striker",
    "Toronto, Ontario",
    "Argentine",
    "Vancouver, BC",
    "The fox in the box.",
    "Argentine-Canadian roots and a poacher's instinct made Cavallini a fan favourite and a reliable goal threat.",
    "Two football cultures, one ruthless instinct in the box.",
  ),
  p(
    "liam-millar",
    "Liam Millar",
    15,
    "Winger",
    "Calgary, Alberta",
    "Scottish",
    "Calgary, Alberta",
    "The prairie prodigy.",
    "Calgary-born with Scottish heritage, Millar represents the next wave of Canadian wingers breaking through in Europe.",
    "The prairies are wide — so is the dream of playing for Canada.",
  ),
  p(
    "dayne-st-clair",
    "Dayne St. Clair",
    12,
    "Goalkeeper",
    "Pickering, Ontario",
    "Trinidadian",
    "Pickering, Ontario",
    "The next-generation keeper.",
    "A Pickering product with Trinidadian heritage who represents the future between the posts for Les Rouges.",
    "Every save is for the kids watching in Pickering who think this path is impossible.",
  ),
  p(
    "maxime-crepeau",
    "Maxime Crépeau",
    21,
    "Goalkeeper",
    "Québec City, QC",
    "French-Canadian",
    "Vancouver, BC",
    "The composed shot-stopper.",
    "Québec-born and Vancouver-based, Crépeau brings calm authority and big-game experience to the squad.",
    "Québec raised me bilingual; Canada made me a goalkeeper.",
  ),
  p(
    "alistair-johnston",
    "Alistair Johnston",
    22,
    "Right Back",
    "Vancouver, BC",
    "Scottish",
    "Vancouver, BC",
    "The modern two-way back.",
    "Vancouver's Scottish-Canadian full-back combines defensive solidity with attacking thrust on the right flank.",
    "Vancouver rain, Scottish grit, Canadian pride — that's my game.",
  ),
  p(
    "sam-piette",
    "Samuel Piette",
    23,
    "Defensive Midfielder",
    "Repentigny, Québec",
    "French-Canadian",
    "Montréal, Québec",
    "The tireless water carrier.",
    "A Montréal-area product whose work rate and humility embody the team-first spirit of Les Rouges.",
    "No spotlight needed — just the honour of wearing red.",
  ),
];

export const WOMENS_SQUAD: Player[] = [
  p(
    "christine-sinclair",
    "Christine Sinclair",
    12,
    "Forward",
    "Burnaby, British Columbia",
    "Canadian",
    "Burnaby, BC",
    "The GOAT. 190 International Goals. The ultimate blueprint of Canadian sports history.",
    "From Burnaby pitches to Olympic gold and a world scoring record, Sinclair built the standard every Canadian player chases.",
    "I wore the maple leaf for decades so every girl in Canada would know her dreams have no ceiling.",
  ),
  p(
    "kadeisha-buchanan",
    "Kadeisha Buchanan",
    3,
    "Centre Back",
    "Brampton, Ontario",
    "Jamaican",
    "Brampton, Ontario",
    "The defensive wall. Multi-time UEFA Champions League winner.",
    "Brampton's Jamaican-Canadian defender became a serial winner at the highest club level in Europe and Canada's defensive cornerstone.",
    "My heritage gave me fire; Canada gave me the platform to become a champion on every continent.",
  ),
  p(
    "ashley-lawrence",
    "Ashley Lawrence",
    10,
    "Full Back / Midfielder",
    "Toronto, Ontario",
    "Jamaican",
    "Toronto, Ontario",
    "World-class versatility. The engine of the Canadian flanks.",
    "Toronto-born with Jamaican heritage, Lawrence redefined what a modern Canadian player could be on the world stage.",
    "Versatility is my heritage story — many roots, one jersey, infinite possibility.",
  ),
  p(
    "vanessa-gilles",
    "Vanessa Gilles",
    14,
    "Centre Back",
    "Montréal, Québec",
    "French",
    "Montréal, Québec",
    "The aerial fortress. Unmatched heart in the penalty box.",
    "Montréal-born with French heritage, Gilles brings uncompromising aerial dominance and emotional leadership to the back line.",
    "Montréal raised me with pride; the maple leaf taught me to stand tall for everyone behind me.",
  ),
  p(
    "jessie-fleming",
    "Jessie Fleming",
    17,
    "Midfielder",
    "London, Ontario",
    "Canadian",
    "London, Ontario",
    "The Olympic final hero.",
    "London, Ontario's own scored the winning penalty in Tokyo — a moment that immortalized her in Canadian sporting history.",
    "One penalty kick in Tokyo — and a nation cried together.",
  ),
  p(
    "quinn",
    "Quinn",
    5,
    "Midfielder",
    "Toronto, Ontario",
    "Canadian",
    "Toronto, Ontario",
    "A pioneer on and off the pitch.",
    "Toronto-born midfielder who became the first openly trans, non-binary athlete to win an Olympic gold medal in any sport.",
    "Visibility matters — and so does winning for the country you love.",
  ),
  p(
    "sophie-schmidt",
    "Sophie Schmidt",
    13,
    "Midfielder",
    "Abbotsford, BC",
    "German",
    "Abbotsford, BC",
    "The midfield general.",
    "Abbotsford-born with German heritage, Schmidt's intelligence and passing range have anchored Canada for over a decade.",
    "German precision, Canadian passion — that's how I play.",
  ),
  p(
    "desiree-scott",
    "Desiree Scott",
    11,
    "Defensive Midfielder",
    "Winnipeg, Manitoba",
    "Jamaican",
    "Winnipeg, MB",
    "The Destroyer. Prairie toughness.",
    "Winnipeg's Jamaican-Canadian midfielder earned her nickname with fearless tackling and a prairie work ethic.",
    "They call me the Destroyer — I call it love for the jersey.",
  ),
  p(
    "erin-mcleod",
    "Erin McLeod",
    1,
    "Goalkeeper",
    "St. Albert, Alberta",
    "Scottish",
    "St. Albert, AB",
    "The veteran presence.",
    "Alberta's Scottish-Canadian keeper whose leadership and shot-stopping defined an era between the posts.",
    "Every clean sheet is a love letter to Alberta's cold mornings on frozen pitches.",
  ),
  p(
    "kailen-sheridan",
    "Kailen Sheridan",
    21,
    "Goalkeeper",
    "Whitby, Ontario",
    "Canadian",
    "Whitby, Ontario",
    "The rising shot-stopper.",
    "A Whitby product whose reflexes and composure represent the next generation of Canadian goalkeeping.",
    "Small-town Ontario, big-stage saves — that's my story.",
  ),
  p(
    "janine-beckie",
    "Janine Beckie",
    16,
    "Forward",
    "Highlands Ranch, Colorado",
    "Canadian",
    "Vancouver, BC",
    "The clinical finisher.",
    "Dual-national forward who chose Canada and became one of the most reliable goal scorers in the squad.",
    "I chose Canada — and Canada chose me back on the biggest stages.",
  ),
  p(
    "adriana-leon",
    "Adriana Leon",
    19,
    "Forward",
    "Maple, Ontario",
    "Mexican",
    "Maple, Ontario",
    "Pace and precision up front.",
    "Maple, Ontario-born with Mexican heritage, Leon's speed and finishing make her a constant threat in attack.",
    "Two cultures, one relentless run in behind the defence.",
  ),
  p(
    "nichelle-prince",
    "Nichelle Prince",
    7,
    "Forward",
    "Ajax, Ontario",
    "Jamaican",
    "Ajax, Ontario",
    "The tricky wide forward.",
    "Ajax-born with Jamaican roots, Prince's dribbling and creativity unlock defences from the flanks.",
    "Jamaican flair on Canadian wings — that's how I create.",
  ),
  p(
    "deanne-rose",
    "Deanne Rose",
    6,
    "Forward",
    "Alliston, Ontario",
    "Jamaican",
    "Alliston, Ontario",
    "Youthful energy and flair.",
    "Alliston's Jamaican-Canadian forward brings youthful exuberance and technical skill to the attack.",
    "I'm young, but my roots run deep — Alliston to Tokyo and beyond.",
  ),
  p(
    "julia-grosso",
    "Julia Grosso",
    8,
    "Midfielder",
    "Vancouver, BC",
    "Italian",
    "Vancouver, BC",
    "The Vancouver playmaker.",
    "Vancouver-born with Italian heritage, Grosso's vision and technique connect Canada's midfield to its attack.",
    "Italian creativity, Vancouver rain, Canadian heart.",
  ),
  p(
    "jayde-riviere",
    "Jayde Riviere",
    2,
    "Right Back",
    "Pickering, Ontario",
    "Jamaican",
    "Pickering, Ontario",
    "The overlapping full-back.",
    "Pickering's Jamaican-Canadian right-back combines defensive discipline with attacking ambition.",
    "Every run down the line is for the girls watching back home in Pickering.",
  ),
  p(
    "jade-rose",
    "Jade Rose",
    4,
    "Centre Back",
    "Cambridge, Ontario",
    "Jamaican",
    "Cambridge, Ontario",
    "The young defensive star.",
    "Cambridge-born with Jamaican heritage, Rose represents the future of Canadian defending at the highest level.",
    "I'm building on a legacy — Sinclair's, Buchanan's, and every defender before me.",
  ),
  p(
    "gabrielle-carle",
    "Gabrielle Carle",
    15,
    "Full Back",
    "Laval, Québec",
    "French-Canadian",
    "Laval, Québec",
    "Québec's defensive stalwart.",
    "Laval-born full-back whose tenacity and tactical intelligence anchor the Canadian back line.",
    "Québec pride in every tackle — that's how I defend.",
  ),
  p(
    "shelina-zadorsky",
    "Shelina Zadorsky",
    18,
    "Centre Back",
    "London, Ontario",
    "Ukrainian",
    "London, Ontario",
    "The aerial powerhouse.",
    "London, Ontario-born with Ukrainian heritage, Zadorsky's aerial ability and leadership are vital in defence.",
    "Ukrainian strength, Canadian determination — I win every header for both.",
  ),
  p(
    "stephanie-labbé",
    "Stephanie Labbé",
    22,
    "Goalkeeper",
    "Stony Plain, Alberta",
    "Canadian",
    "Calgary, AB",
    "Tokyo's hero between the posts.",
    "Alberta's own who made the saves that won Olympic gold — a legend of Canadian goalkeeping.",
    "One save in Tokyo changed my life and my country's history.",
  ),
  p(
    "alyssa-chapman",
    "Alyssa Chapman",
    20,
    "Forward",
    "Calgary, Alberta",
    "Filipino",
    "Calgary, AB",
    "The next-generation striker.",
    "Calgary-born with Filipino heritage, Chapman represents the expanding diversity of Canada's attacking options.",
    "Filipino heart, Alberta hustle, Canadian dreams.",
  ),
  p(
    "bianca-st-georges",
    "Bianca St-Georges",
    9,
    "Forward",
    "Brossard, Québec",
    "Haitian",
    "Brossard, Québec",
    "Speed and power in attack.",
    "Brossard-born with Haitian heritage, St-Georges brings explosive pace and physical presence to the forward line.",
    "Haitian resilience, Québec flair — I run for both communities.",
  ),
  p(
    "emily-zannatto",
    "Emily Zannatto",
    23,
    "Midfielder",
    "Woodbridge, Ontario",
    "Italian",
    "Woodbridge, Ontario",
    "The Italian-Canadian connector.",
    "Woodbridge's Italian-Canadian midfielder whose passing and work rate glue the team together.",
    "Every pass connects my Italian roots to my Canadian future.",
  ),
];
